api=../api
tags=../ref/Tags
github=https://github.com/grace-profiles/profile
sourcedir=.
sourceRepo=https://github.com/grace-profiles/profile/edit/2024.0.x/docs
safe=UNSAFE
title=Grace Profile : Profile
subtitle=A Grace profile to create profile
authors=Michael Yan
copyright=Copyright &copy; 2022-2025 Michael Yan and the original authors. The content is licensed under a Creative Commons Attribution 4.0 International (CC BY SA 4.0) license.
